<script>
SCREENS.activities=()=>{const f=S.actFilter;let list=ACTS;
 if(f==='Ce soir')list=ACTS.filter(a=>a.tonight);if(f==='Ce week-end')list=ACTS.filter(a=>a.we);if(f==='Débutant')list=ACTS.filter(a=>/Débutant|Tous/.test(a.level));if(f==='Mes activités')list=ACTS.filter(a=>S.joined.has(a.id));if(EMO[f])list=ACTS.filter(a=>a.sport===f);
 return `<div class="sc">${head('Activités',`<button class="iconbtn" data-go="map">${I('pin')}</button><button class="iconbtn blue" data-go="create">${I('plus')}</button>`,false)}
 <div class="search">${I('search')}Running, Borély, yoga…</div>
 <div class="hscroll" style="padding-bottom:4px">${['Tous','Ce soir','Ce week-end','Débutant','Mes activités'].map(x=>`<button class="chip ${f===x?'on':''}" data-act="actFilter" data-v="${x}">${x}</button>`).join('')}</div>
 <div class="hscroll">${SPORTS.map(([e,n])=>`<button class="tile ${f===n?'on':''}" style="width:72px;padding:10px 4px;font-size:10.5px" data-act="actFilter" data-v="${n}"><span class="em">${e}</span>${n}</button>`).join('')}</div>
 <div class="row" style="justify-content:space-between"><span class="muted"><b>${list.length}</b> activité${list.length>1?'s':''} · à moins de 10 km</span><span class="tiny">Triées par pertinence</span></div>
 <div style="display:flex;flex-direction:column;gap:14px">${list.map(a=>actCard(a)).join('')||'<div class="card pad muted" style="text-align:center">Aucune activité pour ce filtre.</div>'}</div></div>`;};

SCREENS.activity=({id})=>{const a=A(id)||ACTS[0];const joined=S.joined.has(a.id);const host=U(a.host);
 return `<div class="sc" style="padding-top:0"><div class="scene" style="height:260px;margin:0 -18px;border-radius:0 0 28px 28px">${scene(a.kind)}<button class="iconbtn" data-back style="position:absolute;left:14px;top:12px;background:rgba(255,255,255,.92);border:0;color:var(--navy)">${I('back')}</button><button class="iconbtn" data-act="share" style="position:absolute;right:14px;top:12px;background:rgba(255,255,255,.92);border:0;color:var(--navy)">${I('nav')}</button><span class="tag" style="top:auto;bottom:14px">${EMO[a.sport]} ${a.sport}</span></div>
 <div><h2 style="font-size:26px">${a.title}</h2><div class="muted">Organisé par ${host.name} ${host.verified?`<span class="verified">${I('check')} Vérifié</span>`:''}</div></div>
 <div class="card pad list" style="padding-block:2px"><div class="item">📍<div class="col grow"><b style="font-size:14px">${a.place}</b><span class="tiny">À ${a.dist} · point de rendez-vous précis après inscription</span></div><button class="pill blue" data-go="map">Carte</button></div><div class="item">🗓<div class="col"><b style="font-size:14px">${a.day} · ${a.time}</b><span class="tiny">Durée estimée 1 h 15</span></div></div><div class="item">👥<div class="col grow"><b style="font-size:14px">${a.n} participants · ${a.max-a.n} place${a.max-a.n>1?'s':''} restante${a.max-a.n>1?'s':''}</b><div class="progress" style="margin-top:6px"><i style="width:${a.n/a.max*100}%"></i></div></div></div><div class="item">${EMO[a.sport]}<div class="col"><b style="font-size:14px">Niveau ${a.level.toLowerCase()}</b><span class="tiny">Ton niveau : ${(USERS.me.sports.find(s=>s[0]===a.sport)||['','non renseigné'])[1].toLowerCase()}</span></div></div></div>
 <div><div class="h3" style="margin-bottom:6px">Description</div><p class="muted" style="font-size:14px;line-height:1.5">${a.desc}</p></div>
 <div><div class="row" style="justify-content:space-between;margin-bottom:8px"><div class="h3">Inscrits</div><span class="tiny">${a.n} personnes</span></div><div class="hscroll">${a.who.concat(joined?['me']:[]).map(id=>`<button style="display:flex;flex-direction:column;align-items:center;gap:4px;width:64px" data-go="user" data-id="${id}">${av(id)}<span class="tiny" style="font-weight:700">${U(id).name}</span></button>`).join('')}<div style="display:flex;flex-direction:column;align-items:center;gap:4px;width:64px"><span class="avatar" style="background:var(--sky);color:var(--blue);font-size:13px">+${Math.max(0,a.n-a.who.length-(joined?1:0))}</span><span class="tiny">autres</span></div></div></div>
 <div class="cta-bar">${a.full&&!joined?`<button class="btn btn-outline btn-block" data-act="waitlist" data-id="${a.id}">Rejoindre la liste d'attente</button>`:joined?`<div class="grid2"><button class="btn btn-ghost" data-act="leave" data-id="${a.id}">Se désinscrire</button><button class="btn btn-primary" data-go="chat" data-id="${a.id==='sunset'?'sunsetchat':'running'}">${I('chat')} Ouvrir le chat</button></div>`:`<button class="btn btn-primary btn-block" data-act="join" data-id="${a.id}">Rejoindre l'activité</button>`}</div></div>`;};

SCREENS.create=()=>`<div class="sc">${head('Créer une activité')}<div class="field"><label for="cr-title">Titre</label><input id="cr-title" class="input" placeholder="Ex. Sunset run au Prado" value="Footing découverte Corniche"></div>
 <div class="field"><label>Sport</label><div class="hscroll" style="padding-bottom:2px">${SPORTS.map(([e,n],i)=>`<span class="chip ${i===0?'on':''}">${e} ${n}</span>`).join('')}</div></div>
 <div class="grid2"><div class="field"><label for="cr-day">Date</label><input id="cr-day" class="input" value="Jeu. 9 oct."></div><div class="field"><label for="cr-time">Heure</label><input id="cr-time" class="input" value="18h30"></div></div>
 <div class="field"><label for="cr-place">Lieu de rendez-vous</label><input id="cr-place" class="input" value="Vallon des Auffes, escalier"><span class="tiny">Visible uniquement par les inscrits.</span></div>
 <div class="grid2"><div class="field"><label>Places</label><div class="input row" style="justify-content:space-between"><button data-act="noop">−</button><b>10</b><button data-act="noop">+</button></div></div><div class="field"><label>Niveau</label><div class="seg"><button class="on">Déb.</button><button>Inter.</button><button>Conf.</button></div></div></div>
 <div class="field"><label for="cr-desc">Description</label><textarea id="cr-desc" class="input" rows="3">5 km tranquilles le long de la Corniche, pause photo au Vallon des Auffes. Débutants bienvenus.</textarea></div>
 <label class="row card pad" style="gap:10px;cursor:pointer"><span class="toggle on" data-act="toggleDummy"></span><span class="muted">Réservé aux membres vérifiés</span></label>
 <div class="cta-bar"><button class="btn btn-primary btn-block" data-act="created">Publier l'activité</button></div></div>`;

SCREENS.events=()=>`<div class="sc">${head('Événements','',false)}<div class="seg">${['À venir','Mes événements','Passés'].map(x=>`<button class="${S.evtTab===x?'on':''}" data-act="evtTab" data-v="${x}">${x}</button>`).join('')}</div>
 <div style="display:flex;flex-direction:column;gap:14px">${(S.evtTab==='Mes événements'?EVENTS.filter(e=>S.events.has(e.id)):S.evtTab==='Passés'?[E('runclub')]:EVENTS).map(e=>evtCard(e)).join('')}</div>
 <div class="card pad row" style="gap:12px">${I('plus')}<div class="col grow"><b style="font-size:14px">Proposer un événement communautaire</b><span class="tiny">Ouvert aux membres vérifiés ayant organisé 3 activités.</span></div>${I('arrow')}</div></div>`;

SCREENS.event=({id})=>{const e=E(id)||EVENTS[0];const on=S.events.has(e.id);const rem=S.reminder[e.id]??e.reminder;
 return `<div class="sc" style="padding-top:0"><div class="scene" style="height:250px;margin:0 -18px;border-radius:0 0 28px 28px">${scene(e.kind)}<button class="iconbtn" data-back style="position:absolute;left:14px;top:12px;background:rgba(255,255,255,.92);border:0;color:var(--navy)">${I('back')}</button><span class="tag" style="top:auto;bottom:14px">${e.by==='mars’up'?'⭐ Événement mars’up':e.by==='Partenaire'?'🤝 Partenaire':'👥 Communauté'}</span></div>
 <div><h2 style="font-size:24px">${e.title}</h2><div class="muted">${e.sub}</div></div>
 <div class="card pad list" style="padding-block:2px"><div class="item">📍<b style="font-size:14px">${e.place}</b></div><div class="item">🗓<b style="font-size:14px">${e.day} · ${e.time}</b></div><div class="item">👥<div class="col grow"><b style="font-size:14px">${e.n}/${e.max} places</b><div class="progress" style="margin-top:6px"><i style="width:${e.n/e.max*100}%"></i></div></div><span class="pill ${e.max-e.n<8?'warn':'good'}">${e.max-e.n} restantes</span></div></div>
 <p class="muted" style="font-size:14px;line-height:1.5">${e.desc}</p>
 <div><div class="row" style="justify-content:space-between;margin-bottom:8px"><div class="h3">Participants</div><span class="tiny">${e.n} inscrits</span></div><div class="row">${stack(e.who)}<span class="tiny">${e.who.map(i=>U(i).name).slice(0,3).join(', ')} et ${e.n-3} autres</span></div></div>
 <div class="card pad row settings" style="justify-content:space-between"><div class="row">${I('bell')}<div class="col"><b style="font-size:14px">Rappel avant l'événement</b><span class="tiny">Notification 2 h avant</span></div></div><span class="toggle ${rem?'on':''}" data-act="reminder" data-id="${e.id}"></span></div>
 <div class="cta-bar">${on?`<div class="grid2"><button class="btn btn-ghost" data-act="evtLeave" data-id="${e.id}">Annuler</button><button class="btn btn-primary" data-go="chat" data-id="beachchat">${I('chat')} Chat de l'événement</button></div>`:`<button class="btn btn-primary btn-block" data-act="evtJoin" data-id="${e.id}">S'inscrire · ${e.max-e.n} places</button>`}</div></div>`;};

const chatAv=c=>/^[a-z]+$/.test(c.av)?av(c.av):`<span class="avatar" style="background:var(--sky);font-size:20px">${c.av}</span>`;
SCREENS.messages=()=>{const t=S.chatTab;const map={Privés:'private',Groupes:'group',Activités:'activity',Communauté:'community'};const list=CHATS.filter(c=>t==='Tous'||c.type===map[t]||(t==='Activités'&&c.type==='event'));
 return `<div class="sc">${head('Messages',`<button class="iconbtn" data-act="newChat">${I('edit')}</button>`,false)}<div class="search">${I('search')}Rechercher une conversation</div>
 <div class="hscroll" style="padding-bottom:4px">${['Tous','Privés','Groupes','Activités','Communauté'].map(x=>`<button class="chip ${t===x?'on':''}" data-act="chatTab" data-v="${x}">${x}</button>`).join('')}</div>
 <div class="list">${list.map(c=>{const m=c.msgs[c.msgs.length-1];return `<div class="item" data-go="chat" data-id="${c.id}" style="cursor:pointer">${chatAv(c)}<div class="col grow"><div class="row" style="justify-content:space-between"><b style="font-size:14.5px">${c.title}</b><span class="tiny">${m[2]}</span></div><span class="muted" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;${c.unread?'color:var(--ink);font-weight:600':''}">${m[0]==='me'?'Toi : ':c.type!=='private'?U(m[0]).name+' : ':''}${m[1]}</span></div>${c.unread?`<span class="pill" style="background:var(--blue);color:#fff;min-width:22px;justify-content:center">${c.unread}</span>`:''}</div>`}).join('')}</div></div>`;};

SCREENS.chat=({id})=>{const c=C(id)||CHATS[0];c.unread=0;const priv=c.type==='private';
 return `<div class="sc" style="min-height:100%"><div class="sc-head" style="position:sticky;top:0;background:var(--bg);z-index:2;padding-bottom:6px"><button class="iconbtn" data-back>${I('back')}</button>${chatAv(c)}<div class="col grow" ${priv?`data-go="user" data-id="${c.av}" style="cursor:pointer"`:''}><b style="font-size:15px">${c.title}</b><span class="tiny">${c.sub}${priv?' · en ligne':''}</span></div>${c.type==='activity'||c.type==='event'?`<button class="iconbtn" data-go="${c.type}" data-id="${c.type==='activity'?'sunset':'beachday'}">${I('info')}</button>`:''}<button class="iconbtn" data-act="chatMenu" data-id="${c.id}">${I('more')}</button></div>
 ${c.type!=='private'?`<div class="card pad row" style="gap:10px;background:var(--sky);border-color:transparent;padding:10px 12px">${I('shield')}<span class="tiny" style="color:var(--blue)">Conversation protégée. Les numéros et adresses ne sont jamais partagés automatiquement. Signale tout comportement déplacé.</span></div>`:''}
 <div class="tiny" style="text-align:center">Aujourd'hui</div>
 <div class="bubbles" id="bubbles">${c.msgs.map(m=>`<div class="bub ${m[0]==='me'?'me':''}">${m[0]!=='me'&&!priv?`<span class="who">${U(m[0]).name}</span>`:''}${m[1]}<span class="t">${m[2]}</span></div>`).join('')}</div>
 <div class="sugg" style="margin-top:auto">${['On se retrouve à 18h15 ? 👍','Vous partez d\'où ?','J\'arrive !'].map(q=>`<button data-act="quick" data-id="${c.id}" data-v="${esc(q)}">${q}</button>`).join('')}</div>
 <div class="composer"><button class="iconbtn" data-act="noop">${I('image')}</button><input class="input" id="msg-${c.id}" placeholder="Écrire un message…"><button class="iconbtn blue" data-act="send" data-id="${c.id}">${I('send')}</button></div></div>`;};

SCREENS.map=()=>{const f=S.mapFilter;const sel=S.mapPlace;const acts=sel?ACTS.filter(a=>a.map===sel):[];const show=Object.entries(PLACES).filter(([k])=>f==='Tous'||ACTS.some(a=>a.map===k&&a.sport===f)||(f==='Événements'&&['catalans','borely','prado','coursju','luminy'].includes(k)));
 const land='M130 0H360V440H260c-20-12-45-22-70-14s-50-21-68-44c-14-20-12-52-6-82 6-28-20-48-30-74-10-24 6-44 26-56l58-4c5-1 6-16 0-17l-58-3c-8-16-8-34-4-46 4-20 10-60 22-100z';
 return `<div class="sc">${head('Carte',`<button class="iconbtn" data-act="locate">${I('nav')}</button>`,false)}
 <div class="mapwrap"><div class="map-float">${['Tous','Running','Basket','Beach-volley','Football','Yoga','Nautique','Événements'].map(x=>`<button class="chip ${f===x?'on':''}" data-act="mapFilter" data-v="${x}">${EMO[x]||''} ${x}</button>`).join('')}</div>
 <svg viewBox="0 0 360 440" role="img" aria-label="Carte de Marseille avec les activités">
  <defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#fff" stroke-width=".8" opacity=".45"/></pattern></defs>
  <rect width="360" height="440" fill="#BFDDFF"/>
  <path d="M0 120c30-10 50 10 80 0M0 260c30-12 60 12 90 0M0 400c30-10 50 10 80 0" stroke="#fff" stroke-width="2" fill="none" opacity=".7"/>
  <path d="${land}" fill="#F4F8FE"/><path d="${land}" fill="url(#grid)"/>
  <ellipse cx="44" cy="150" rx="18" ry="8" fill="#F4F8FE"/><ellipse cx="52" cy="176" rx="22" ry="9" fill="#F4F8FE"/><circle cx="70" cy="158" r="5" fill="#F4F8FE"/>
  <ellipse cx="150" cy="332" rx="30" ry="20" fill="#D7EFD9"/><ellipse cx="236" cy="112" rx="22" ry="14" fill="#D7EFD9"/><ellipse cx="300" cy="400" rx="30" ry="16" fill="#D7EFD9"/>
  <path d="M182 160L206 214 190 286 152 332M206 214L300 398M182 160L236 112M112 184L98 216 126 300 128 380 196 416M206 214L216 176M130 60L182 160" stroke="#DCE6F5" stroke-width="5" fill="none" stroke-linecap="round"/>
  <g font-family="Manrope,sans-serif" font-size="9" fill="#4A5B78" font-weight="700"><text x="196" y="140">Vieux-Port</text><text x="60" y="235">Corniche</text><text x="138" y="290">Prado</text><text x="140" y="398">Pointe Rouge</text><text x="210" y="434">Calanques</text><text x="28" y="140">Frioul</text><text x="226" y="100">Longchamp</text></g>
  <g><circle cx="200" cy="222" r="26" fill="#0F6BFF" opacity=".12"/><circle cx="200" cy="222" r="7" fill="#0F6BFF" stroke="#fff" stroke-width="3"/></g>
  ${show.map(([k,p])=>{const n=ACTS.filter(a=>a.map===k).length;return `<g class="pin ${sel===k?'on':''}" data-act="place" data-v="${k}" transform="translate(${p.x} ${p.y})"><circle class="b" r="14"/><text text-anchor="middle" dy="4.5">${p.em}</text>${n>1?`<circle cx="12" cy="-12" r="7" fill="#07234F" stroke="#fff" stroke-width="2"/><text x="12" y="-9" text-anchor="middle" font-size="8" fill="#fff" font-weight="800">${n}</text>`:''}</g>`}).join('')}
 </svg></div>
 ${sel?`<div class="card pad"><div class="row" style="justify-content:space-between;margin-bottom:10px"><div><div class="h3">${PLACES[sel].name}</div><span class="tiny">${acts.length||1} activité${acts.length>1?'s':''} · lieu populaire</span></div><button class="iconbtn" data-act="place" data-v="">${I('x')}</button></div>
 <div class="list">${acts.map(a=>`<div class="item" data-go="activity" data-id="${a.id}" style="cursor:pointer"><span class="avatar" style="background:var(--sky);font-size:20px">${EMO[a.sport]}</span><div class="col grow"><b style="font-size:14px">${a.title}</b><span class="tiny">${a.day} ${a.time} · 👥 ${a.n}/${a.max} · ${a.level}</span></div>${I('arrow')}</div>`).join('')||`<div class="item"><span class="avatar" style="background:var(--sky);font-size:20px">${PLACES[sel].em}</span><div class="col grow"><b style="font-size:14px">Terrain / lieu de pratique</b><span class="tiny">Aucune activité programmée. Sois la première à en créer une.</span></div><button class="pill blue" data-go="create">Créer</button></div>`}</div></div>`:
 `<div class="row" style="justify-content:space-between"><span class="muted"><b>${show.length}</b> lieux · <b>${ACTS.length}</b> activités autour de toi</span><span class="tiny">Touche un marqueur</span></div>
 <div class="hscroll">${ACTS.slice(0,5).map(a=>actCard(a,'act-card act-mini')).join('')}</div>`}</div>`;};

const AI_ANSWERS=[
 {q:/mardi|nouveau|20 ans|sport/i,a:()=>`Bienvenue à Marseille 👋 Voici 3 activités près de toi mardi soir, adaptées à ton niveau :`,acts:['basket','swim','gym'],tail:'Je peux t\'inscrire à l\'une d\'elles ou te présenter les personnes qui y vont.'},
 {q:/groupe|créer/i,a:()=>`D'après ton questionnaire (running débutant, 6e, mardi et jeudi soir), voici un groupe que je te propose de créer :`,group:true,tail:'7 membres compatibles seraient invités automatiquement. Je lance ?'},
 {q:/personne|qui|correspond|rencontr/i,a:()=>`Trois personnes partagent tes sports, ton quartier et tes créneaux :`,people:['yanis','lea','camille'],tail:'Tu peux les retrouver dans Découvrir ou leur écrire directement.'},
 {q:/week|samedi|dimanche|plage|mer/i,a:()=>`Ce week-end, côté mer et plein air, je te conseille :`,acts:['bv','yoga','paddle'],tail:'Le Beach Day de dimanche affiche encore 6 places, c\'est le meilleur moyen de rencontrer la communauté.'},
 {q:/.*/,a:()=>`Je peux t'aider à trouver une activité, des personnes compatibles, un événement, ou créer un groupe selon tes disponibilités. Dis-moi quand tu es libre et ce que tu aimes.`,tail:''},
];
SCREENS.ai=()=>`<div class="sc" style="min-height:100%"><div class="sc-head" style="position:sticky;top:0;background:var(--bg);z-index:2"><button class="iconbtn" data-back>${I('back')}</button><span class="avatar" style="background:linear-gradient(135deg,var(--navy),var(--blue))">${I('sparkles')}</span><div class="col grow"><b style="font-size:15px">IA mars’up</b><span class="tiny">Ton coach de quartier · répond en quelques secondes</span></div></div>
 <div class="bubbles">${S.aiLog.length?S.aiLog.join(''):`<div class="bub">Salut Lola ! Je connais toutes les activités de Marseille et ton profil. Pose-moi une question ou choisis une suggestion 👇</div>`}</div>
 <div class="sugg" style="margin-top:auto">${['Je suis nouvelle à Marseille, j\'ai 20 ans et je cherche à faire du sport mardi soir.','Crée-moi un groupe','Qui me correspond ?','Quoi faire ce week-end côté mer ?'].map(q=>`<button data-act="ask" data-v="${esc(q)}">${q}</button>`).join('')}</div>
 <div class="composer"><input class="input" id="ai-input" placeholder="Demande à l'IA mars’up…"><button class="iconbtn blue" data-act="askInput">${I('send')}</button></div>
 <p class="tiny" style="text-align:center">L'IA n'a accès qu'aux données de ton profil et aux activités publiques. Rien n'est partagé avec d'autres membres.</p></div>`;

const NOTIF_ICO={match:'heart',msg:'chat',near:'pin',event:'calendar',ai:'sparkles',invite:'users',verif:'shield'};
SCREENS.notifications=()=>{S.notifRead=true;return `<div class="sc">${head('Notifications',`<button class="iconbtn" data-go="settings">${I('gear')}</button>`)}
 <div class="seg"><button class="on">Toutes</button><button>Matchs</button><button>Messages</button><button>Activités</button></div>
 <div><div class="tiny" style="font-weight:800;margin-bottom:4px">AUJOURD'HUI</div><div>${NOTIFS.slice(0,4).map(n=>`<div class="notif ${n.unread?'unread':''}" data-go="${n.go}" ${n.id?`data-id="${n.id}"`:''} style="cursor:pointer"><span class="ic">${I(NOTIF_ICO[n.t])}</span><div class="col grow"><b style="font-size:14px">${n.title}</b><span class="muted">${n.sub}</span><span class="tiny">${n.time}</span></div></div>`).join('')}</div></div>
 <div><div class="tiny" style="font-weight:800;margin-bottom:4px">CETTE SEMAINE</div><div>${NOTIFS.slice(4).map(n=>`<div class="notif" data-go="${n.go}" ${n.id?`data-id="${n.id}"`:''} style="cursor:pointer"><span class="ic">${I(NOTIF_ICO[n.t])}</span><div class="col grow"><b style="font-size:14px">${n.title}</b><span class="muted">${n.sub}</span><span class="tiny">${n.time}</span></div></div>`).join('')}</div></div></div>`;};

const profileBody=(u,me)=>`<div class="sc" style="padding-top:0"><div class="prof-head"><div class="sc-head" style="color:#fff">${me?`<span class="brand"><svg class="mark" style="height:26px"><use href="#mu-mark"/></svg></span><span class="grow"></span><button class="iconbtn" data-go="settings" style="background:rgba(255,255,255,.15);border:0;color:#fff">${I('gear')}</button>`:`<button class="iconbtn" data-back style="background:rgba(255,255,255,.15);border:0;color:#fff">${I('back')}</button><span class="grow"></span><button class="iconbtn" data-act="userMenu" data-id="${u.id}" style="background:rgba(255,255,255,.15);border:0;color:#fff">${I('more')}</button>`}</div></div>
 <div class="prof-card">${av(u,'xl')}<div class="h3" style="font-size:24px">${u.name}, ${u.age} ${u.verified?`<span class="verified">${I('check')} Profil vérifié</span>`:'<span class="pill warn">Non vérifié</span>'}</div><div class="muted">📍 ${u.sector}</div></div>
 ${me?`<div class="statrow card pad"><div><b>14</b><span>activités</span></div><div><b>6</b><span>matchs</span></div><div><b>3</b><span>groupes</span></div></div>`:`<div class="grid2"><button class="btn btn-ghost" data-act="inviteUser" data-id="${u.id}">${I('activity')} Rejoindre une activité</button><button class="btn btn-primary" data-go="chat" data-id="${C(u.id)?u.id:'yanis'}">${I('chat')} Discuter</button></div>`}
 <div class="card pad" style="display:flex;flex-direction:column;gap:12px">
  <div><div class="tiny" style="font-weight:800;margin-bottom:6px">SPORTS & NIVEAU</div><div class="chips" style="gap:6px">${sportsPills(u)}</div></div>
  <div><div class="tiny" style="font-weight:800;margin-bottom:6px">CENTRES D'INTÉRÊT</div><div class="chips" style="gap:6px">${u.interests.map(i=>`<span class="pill">${i}</span>`).join('')}</div></div>
  <div><div class="tiny" style="font-weight:800;margin-bottom:6px">DISPONIBILITÉS</div><div class="muted">📅 ${u.dispo}</div></div>
  <div><div class="tiny" style="font-weight:800;margin-bottom:6px">À PROPOS</div><p class="muted" style="font-size:14px;line-height:1.5">${u.bio}</p></div></div>
 ${me?`<div><div class="h3" style="margin-bottom:8px">Mes prochaines activités</div><div style="display:flex;flex-direction:column;gap:12px">${ACTS.filter(a=>S.joined.has(a.id)).map(a=>actCard(a)).join('')||'<div class="muted">Aucune activité à venir.</div>'}</div></div>
 <button class="btn btn-outline btn-block" data-act="editProfile">${I('edit')} Modifier mon profil</button>`:`<div><div class="h3" style="margin-bottom:8px">Activités de ${u.name}</div><div style="display:flex;flex-direction:column;gap:12px">${ACTS.filter(a=>a.who.includes(u.id)||a.host===u.id).slice(0,2).map(a=>actCard(a)).join('')}</div></div>
 <div class="row tiny" style="justify-content:center;gap:14px"><button data-act="report" data-id="${u.id}" style="display:inline-flex;gap:4px;align-items:center">${I('flag')} Signaler</button><button data-act="block" data-id="${u.id}" style="display:inline-flex;gap:4px;align-items:center">${I('ban')} Bloquer</button></div>`}</div>`;
SCREENS.profile=()=>profileBody(USERS.me,true);
SCREENS.user=({id})=>profileBody(U(id)||USERS.yanis,false);

SCREENS.settings=()=>{const s=S.settings;const row=(ic,t,sub,key)=>`<div class="item">${I(ic)}<div class="col grow"><b style="font-size:14px">${t}</b><span class="tiny">${sub}</span></div><span class="toggle ${s[key]?'on':''}" data-act="setting" data-v="${key}"></span></div>`;
 return `<div class="sc">${head('Confidentialité & sécurité')}
 <div><div class="tiny" style="font-weight:800;margin-bottom:6px">VISIBILITÉ DU PROFIL</div><div class="seg">${['Tout le monde','Membres vérifiés','Mes groupes'].map(x=>`<button class="${s.vis===x?'on':''}" data-act="vis" data-v="${x}">${x}</button>`).join('')}</div></div>
 <div class="card pad list settings" style="padding-block:2px">${row('eye','Afficher mes disponibilités','Visible sur ton profil public','dispo')}${row('pin','Localisation approximative','Arrondissement uniquement, jamais l\'adresse','geo')}${row('bell','Notifications push','Matchs, messages, rappels d\'événements','notif')}${row('chart','Statistiques d\'usage anonymisées','Aide à améliorer mars’up · désactivé par défaut','stats')}</div>
 <div><div class="tiny" style="font-weight:800;margin-bottom:6px">MES DONNÉES (RGPD)</div><div class="card pad list settings" style="padding-block:2px"><div class="item" data-act="exportData" style="cursor:pointer">${I('download')}<div class="col grow"><b style="font-size:14px">Exporter mes données</b><span class="tiny">Archive envoyée par e-mail sous 48 h</span></div>${I('arrow')}</div><div class="item" data-act="consent" style="cursor:pointer">${I('shield')}<div class="col grow"><b style="font-size:14px">Gérer mes consentements</b><span class="tiny">Vérification d'identité, géolocalisation, communications</span></div>${I('arrow')}</div><div class="item" data-act="deleteAccount" style="cursor:pointer;color:var(--bad)">${I('trash')}<div class="col grow"><b style="font-size:14px">Supprimer mon compte</b><span class="tiny">Effacement complet sous 30 jours</span></div></div></div></div>
 <div><div class="tiny" style="font-weight:800;margin-bottom:6px">SÉCURITÉ</div><div class="card pad list settings" style="padding-block:2px"><div class="item">${I('ban')}<div class="col grow"><b style="font-size:14px">Comptes bloqués</b><span class="tiny">1 compte</span></div>${I('arrow')}</div><div class="item">${I('lock')}<div class="col grow"><b style="font-size:14px">Connexion & appareils</b><span class="tiny">Double authentification activée</span></div>${I('arrow')}</div><div class="item" data-act="report" data-id="" style="cursor:pointer">${I('flag')}<div class="col grow"><b style="font-size:14px">Signaler un problème</b><span class="tiny">Réponse de la modération sous 24 h</span></div>${I('arrow')}</div></div></div></div>`;};

/* ---------- Actions ---------- */
const ACTIONS={
 noop(){},toggleDummy(_,__,b){b.classList.toggle('on')},
 suNext(){if(S.signup.step<8){S.signup.step++;render();screenEl.scrollTop=0;}else{S.verify.step=0;go('verify');}},
 suPrev(){S.signup.step--;render();},
 sector(_,v){S.signup.sector=v;render();},
 interest(_,v){const a=S.signup.interests;a.includes(v)?a.splice(a.indexOf(v),1):a.push(v);render();},
 sport(_,v){const s=S.signup.sports;s[v]?delete s[v]:s[v]='Débutant';render();},
 level(id,v){S.signup.sports[id]=v;render();},
 dispo(_,v){const d=S.signup.dispo;d[v]?delete d[v]:d[v]=1;render();},
 size(_,v){S.signup.size=v;render();},goal(_,v){S.signup.goal=v;render();},
 discover(_,v){const a=S.signup.discover;a.includes(v)?a.splice(a.indexOf(v),1):a.push(v);render();},
 vNext(){S.verify.step++;render();screenEl.scrollTop=0;if(S.verify.step===3)setTimeout(()=>toast('Identité confirmée par le prestataire','shield'),400);},
 vPrev(){S.verify.step--;render();},vDoc(_,v){S.verify.doc=v;render();},
 actFilter(_,v){S.actFilter=S.actFilter===v&&v!=='Tous'?'Tous':v;render();},
 join(id){const a=A(id);S.joined.add(id);a.n++;render();toast(`Tu as rejoint « ${a.title} ». Chat ouvert.`);},
 leave(id){const a=A(id);S.joined.delete(id);a.n--;render();toast('Désinscription prise en compte','x');},
 waitlist(){toast('Tu seras prévenue si une place se libère','bell');},
 share(){toast('Lien de l\'activité copié','nav');},
 created(){toast('Activité publiée ! Visible par les membres à moins de 10 km');go('activities');},
 evtTab(_,v){S.evtTab=v;render();},
 evtJoin(id){const e=E(id);S.events.add(id);e.n++;render();toast(`Inscrite au ${e.title}. Rappel 2 h avant.`,'calendar');},
 evtLeave(id){const e=E(id);S.events.delete(id);e.n--;render();toast('Inscription annulée','x');},
 reminder(id,_,b){S.reminder[id]=!b.classList.contains('on');b.classList.toggle('on');toast(S.reminder[id]?'Rappel activé 2 h avant':'Rappel désactivé','bell');},
 chatTab(_,v){S.chatTab=v;render();},
 send(id){const inp=$('#msg-'+id);const t=inp&&inp.value.trim();if(!t)return;ACTIONS.quick(id,t);},
 quick(id,v){const c=C(id);c.msgs.push(['me',esc(v),'maintenant']);render();screenEl.scrollTop=screenEl.scrollHeight;const replies={yanis:'Top ! Départ 18h30 devant le Pharo, je t\'envoie le point exact.',lea:'Parfait, à dimanche 🏐',running:'Ça marche pour moi 👍',sunsetchat:'Nickel, on se voit samedi !',beachchat:'Génial, merci !',newbies:'Bienvenue ! 👋'};const from=c.type==='private'?c.av:['yanis','lea','ines','tom'].filter(x=>x!==c.av)[0];setTimeout(()=>{c.msgs.push([from,replies[id]||'👍','maintenant']);if(S.screen==='chat'&&S.params.id===id){render();screenEl.scrollTop=screenEl.scrollHeight;}},1200);},
 newChat(){toast('Choisis un match ou un groupe pour démarrer une conversation','chat');},
 chatMenu(id){sheet(`<div class="h3">Options de la conversation</div><div class="list"><div class="item">${I('bell')}<b style="font-size:14px">Mettre en sourdine</b></div><div class="item">${I('users')}<b style="font-size:14px">Voir les participants</b></div><div class="item" data-act="report" data-id="${id}" style="color:var(--bad)">${I('flag')}<b style="font-size:14px">Signaler la conversation</b></div><div class="item" style="color:var(--bad)">${I('ban')}<b style="font-size:14px">Quitter le groupe</b></div></div>`);},
 mapFilter(_,v){S.mapFilter=v;S.mapPlace=null;render();},
 place(_,v){S.mapPlace=v||null;render();if(v)setTimeout(()=>screenEl.scrollTo({top:screenEl.scrollHeight,behavior:'smooth'}),50);},
 locate(){toast('Position approximative : Marseille 5e','nav');},
 deckMode(_,v){S.deckMode=v;render();},
 resetDeck(){S.deck=['yanis','lea','ines','mehdi','camille','tom'];render();},
 filters(){sheet(`<div class="h3">Filtres de découverte</div><div class="field"><label>Distance · 5 km</label><input type="range" min="1" max="20" value="5" style="accent-color:var(--blue)"></div><div class="field"><label>Âge · 18 – 28 ans</label><input type="range" min="18" max="45" value="28" style="accent-color:var(--blue)"></div><div class="field"><label>Niveau</label><div class="seg"><button>Débutant</button><button class="on">Tous</button><button>Confirmé</button></div></div><div class="field"><label>Sports</label><div class="chips">${SPORTS.slice(0,6).map(([e,n],i)=>`<span class="chip ${i<3?'on':''}">${e} ${n}</span>`).join('')}</div></div><button class="btn btn-primary btn-block" data-act="closeSheet">Appliquer</button>`);},
 closeSheet(){closeSheet();},
 info(){if(S.deckMode==='Personnes'&&S.deck[0])go('user',{id:S.deck[0]});else if(S.deckMode==='Activités')go('activity',{id:(ACTS.filter(x=>!S.joined.has(x.id))[0]||ACTS[2]).id});else if(S.deckMode==='Événements')go('event',{id:'afterwork'});else toast('Groupe proposé par l\'IA mars’up','sparkles');},
 swipe(_,v){const top=screenEl.querySelector('.swipe.top');if(!top)return;top.classList.add(v==='like'?'out-r':'out-l');
  setTimeout(()=>{if(S.deckMode==='Personnes'){const id=S.deck.shift();if(v==='like'){S.likes.add(id);if(['yanis','lea'].includes(id)){render();return matchSheet(id);}toast(`Tu veux bouger avec ${U(id).name}. On lui dit !`,'heart');}}
   else if(S.deckMode==='Activités'){const a=ACTS.filter(x=>!S.joined.has(x.id))[0];if(v==='like'&&a){S.joined.add(a.id);a.n++;toast(`Inscrite à « ${a.title} »`);}else S.deckIdx=(S.deckIdx||0)+1;}
   else if(S.deckMode==='Groupes'){if(v==='like')toast('Tu as rejoint « Hand & running débutant 5e »','users');S.deckMode='Événements';}
   else{if(v==='like'){S.events.add('afterwork');toast('Inscrite à l\'Afterwork des nouveaux','calendar');}S.deckMode='Personnes';}
   render();},330);},
 ask(_,v){askAI(v);},askInput(){const i=$('#ai-input');if(i&&i.value.trim())askAI(i.value.trim());},
 aiJoin(id){ACTIONS.join(id);},
 aiGroup(){S.aiLog.push(`<div class="bub">C'est fait ✅ Le groupe « Hand & running débutant 5e » est créé et 7 membres compatibles ont reçu une invitation. Je t'ai ouvert le chat du groupe.</div>`);render();toast('Groupe créé · 7 invitations envoyées','users');},
 setting(_,v){S.settings[v]=!S.settings[v];render();},vis(_,v){S.settings.vis=v;render();toast('Visibilité mise à jour : '+v,'eye');},
 exportData(){toast('Export demandé. Archive envoyée sous 48 h.','download');},consent(){toast('Consentements : vérification ✓, géoloc approx. ✓, marketing ✗','shield');},
 deleteAccount(){sheet(`<div class="h3" style="color:var(--bad)">Supprimer mon compte ?</div><p class="muted">Tes données personnelles, messages et participations seront effacés définitivement sous 30 jours, conformément au RGPD. Le statut de vérification est révoqué immédiatement.</p><div class="grid2"><button class="btn btn-outline" data-act="closeSheet">Annuler</button><button class="btn" style="background:var(--bad);color:#fff" data-act="closeSheet">Confirmer</button></div>`);},
 report(id){sheet(`<div class="h3">Signaler ${id&&U(id)?U(id).name:'un problème'}</div><p class="muted">Ton signalement est confidentiel et traité par la modération sous 24 h.</p><div class="list">${['Comportement inapproprié','Faux profil / usurpation','Propos haineux ou harcèlement','Contenu hors sujet (rencontre amoureuse, pub)','Autre'].map(r=>`<div class="item" data-act="reportSend" style="cursor:pointer"><b style="font-size:14px">${r}</b><span style="margin-left:auto">${I('arrow')}</span></div>`).join('')}</div>`);},
 reportSend(){closeSheet();toast('Signalement envoyé à la modération. Merci.','flag');},
 block(id){closeSheet();toast(`${U(id).name} est bloqué·e. Vous ne vous verrez plus.`,'ban');back();},
 userMenu(id){sheet(`<div class="h3">${U(id).name}</div><div class="list"><div class="item" data-act="inviteUser" data-id="${id}" style="cursor:pointer">${I('activity')}<b style="font-size:14px">Inviter à une activité</b></div><div class="item" data-act="share" style="cursor:pointer">${I('nav')}<b style="font-size:14px">Partager le profil</b></div><div class="item" data-act="report" data-id="${id}" style="cursor:pointer;color:var(--bad)">${I('flag')}<b style="font-size:14px">Signaler</b></div><div class="item" data-act="block" data-id="${id}" style="cursor:pointer;color:var(--bad)">${I('ban')}<b style="font-size:14px">Bloquer</b></div></div>`);},
 inviteUser(id){sheet(`<div class="h3">Inviter ${U(id).name} à…</div><div class="list">${ACTS.filter(a=>S.joined.has(a.id)).map(a=>`<div class="item" data-act="inviteSend" data-id="${id}" style="cursor:pointer"><span class="avatar sm" style="background:var(--sky);font-size:16px">${EMO[a.sport]}</span><div class="col grow"><b style="font-size:14px">${a.title}</b><span class="tiny">${a.day} ${a.time}</span></div>${I('arrow')}</div>`).join('')}</div>`);},
 inviteSend(id){closeSheet();toast(`Invitation envoyée à ${U(id).name}`,'send');},
 editProfile(){S.signup.step=6;go('signup');},
};
function matchSheet(id){const u=U(id);sheet(`<div style="font-size:13px;font-weight:800;letter-spacing:.1em;opacity:.8">C'EST UN MATCH SPORTIF</div><h2 style="font-size:28px;color:#fff">Toi et ${u.name}, ${u.score} % compatibles</h2><div class="row" style="gap:-8px">${av('me','lg')}<span style="font-size:28px;margin:0 -6px;z-index:1">🤝</span>${av(u,'lg')}</div><p style="opacity:.85;font-size:14px">${u.why.join(' · ')}</p><div class="chips" style="justify-content:center">${u.sports.map(s=>`<span class="pill" style="background:rgba(255,255,255,.18);color:#fff">${EMO[s[0]]} ${s[0]}</span>`).join('')}</div><button class="btn btn-block" style="background:#fff;color:var(--navy)" data-go="chat" data-id="${id}">${I('chat')} Discuter avec ${u.name}</button><button class="btn btn-block" style="background:rgba(255,255,255,.14);color:#fff" data-go="activity" data-id="${id==='yanis'?'sunset':'bv'}">Proposer une activité</button><button style="opacity:.8;font-size:13px" data-act="closeSheet">Continuer à découvrir</button>`,'match');}
function askAI(q){const r=AI_ANSWERS.find(x=>x.q.test(q));S.aiLog.push(`<div class="bub me">${esc(q)}</div>`);render();screenEl.scrollTop=screenEl.scrollHeight;
 setTimeout(()=>{let h=`<div class="bub" style="max-width:92%">${r.a()}`;
  if(r.acts)h+=`<div class="ai-res">${r.acts.map(id=>{const a=A(id);return `<div class="mini"><span class="scene">${scene(a.kind)}</span><div class="col grow"><b style="font-size:13px">${a.title}</b><span class="tiny">${a.place} · ${a.day} ${a.time} · ${a.level}</span></div>${S.joined.has(id)?'<span class="pill good">✓</span>':`<button class="pill blue" data-act="aiJoin" data-id="${id}">Rejoindre</button>`}</div>`}).join('')}</div>`;
  if(r.people)h+=`<div class="ai-res">${r.people.map(id=>{const u=U(id);return `<div class="mini" data-go="user" data-id="${id}" style="cursor:pointer">${av(u)}<div class="col grow"><b style="font-size:13px">${u.name}, ${u.age} · ${u.sector}</b><span class="tiny">${u.sports.map(s=>s[0]).join(', ')} · ${u.score} %</span></div>${I('arrow')}</div>`}).join('')}</div>`;
  if(r.group)h+=`<div class="ai-res"><div class="mini" style="flex-direction:column;align-items:stretch;gap:6px"><b style="font-size:14px">🏃 Hand & running débutant 5e</b><span class="tiny">Mardi & jeudi 19h · départ Castellane · 5 km allure 7:00</span><div class="row">${stack(['camille','tom','ines','mehdi'])}<span class="tiny">7 membres compatibles</span></div><button class="btn btn-primary btn-sm" data-act="aiGroup">Créer ce groupe et inviter</button></div></div>`;
  if(r.tail)h+=`<p class="tiny" style="margin-top:8px;color:inherit;opacity:.7">${r.tail}</p>`;h+='</div>';S.aiLog.push(h);if(S.screen==='ai'){render();screenEl.scrollTop=screenEl.scrollHeight;}},900);}

/* ---------- Geste de swipe (tactile et souris) sur la carte du haut ---------- */
let drag=null;
screenEl.addEventListener('pointerdown',e=>{const c=e.target.closest('.swipe.top');if(!c||e.target.closest('button,[data-go]'))return;drag={c,x:e.clientX,y:e.clientY,dx:0};c.classList.add('drag');try{c.setPointerCapture(e.pointerId)}catch(_){}});
screenEl.addEventListener('pointermove',e=>{if(!drag)return;drag.dx=e.clientX-drag.x;const dy=e.clientY-drag.y;drag.c.style.transform=`translate(${drag.dx}px,${dy*0.25}px) rotate(${drag.dx/18}deg)`;});
const endDrag=()=>{if(!drag)return;const {c,dx}=drag;drag=null;c.classList.remove('drag');c.style.transform='';if(Math.abs(dx)>90)ACTIONS.swipe(null,dx>0?'like':'pass');};
screenEl.addEventListener('pointerup',endDrag);screenEl.addEventListener('pointercancel',endDrag);
</script>
