<script>
/* ---------- Amis & géolocalisation (type Snap Map, limitée aux amis acceptés) ---------- */
Object.assign(USERS.me,{loc:{x:200,y:222},place:'Castellane'});
const FLOC={yanis:['borely','il y a 3 min','sunset','precise'],lea:['catalans','il y a 12 min','bv','precise'],ines:['auffes','il y a 25 min',null,'area'],mehdi:['prado','il y a 1 min','basket','precise'],camille:['longchamp','il y a 40 min',null,'area'],tom:['pointerouge','il y a 8 min','paddle','precise'],nour:['luminy','il y a 2 h',null,'area'],hugo:['sormiou','il y a 1 h',null,'area']};
Object.entries(FLOC).forEach(([id,[p,seen,doing,share]])=>Object.assign(USERS[id],{loc:PLACES[p],place:PLACES[p].name,seen,doing,share}));
Object.assign(S,{friends:new Set(['yanis','lea','camille']),reqIn:['ines','tom'],reqOut:new Set(),ghost:false,shareMode:'Quartier',mapMode:'Activités',mapFriend:null});
S.settings.shareLoc=true;
NOTIFS.unshift(
 {t:'friend',title:"Inès t'a envoyé une demande d'ami",sub:'Yoga · Marseille 5e · 2 activités en commun',time:'il y a 2 min',unread:true,act:'openFriends'},
 {t:'near',title:'Yanis est au Parc Borély',sub:'À 1,8 km de toi, en Sunset Run. Tu le rejoins ?',time:'il y a 10 min',unread:true,act:'focusFriend',id:'yanis'});
NOTIF_ICO.friend='users';
AI_ANSWERS.unshift({q:/ami|pote|copain|copine/i,a:()=>'Trois de tes amis bougent en ce moment :',people:['yanis','lea','mehdi'],tail:'Ouvre la carte des amis pour les rejoindre, ou ajoute de nouveaux amis depuis Découvrir.'});

const AVC=['#0F6BFF','#07234F','#1F8EF1','#0A4FC2','#153B7A'];
const AREA=u=>u.sector.replace('Marseille ','');
const whereTxt=u=>u.doing?`🟢 En activité · ${A(u.doing).title}`:u.share==='precise'?`📍 ${u.place} · ${u.seen}`:`📍 Quartier ${AREA(u)} · ${u.seen}`;
const relation=id=>S.friends.has(id)?'friend':S.reqOut.has(id)?'sent':S.reqIn.includes(id)?'incoming':'none';
const friendBtn=(id,cls='')=>{const r=relation(id);return r==='friend'?`<button class="btn btn-ghost ${cls}" data-act="friendMenu" data-id="${id}">${I('check')} Amis</button>`:r==='sent'?`<button class="btn btn-outline ${cls}" data-act="cancelReq" data-id="${id}" style="color:var(--ink-2)">${I('clock')} Demande envoyée</button>`:r==='incoming'?`<button class="btn btn-primary ${cls}" data-act="acceptReq" data-id="${id}">${I('check')} Accepter la demande d'ami</button>`:`<button class="btn btn-outline ${cls}" data-act="addFriend" data-id="${id}">${I('plus')} Ajouter en ami</button>`;};
const friendsRow=()=>`<div><div class="section-head" style="margin-bottom:10px"><h3 class="h3">Tes amis en ce moment</h3><button class="tiny" style="color:var(--blue);font-weight:700" data-act="mapFriends">Carte des amis</button></div><div class="hscroll">${[...S.friends].map(id=>{const u=U(id);return `<button style="display:flex;flex-direction:column;align-items:center;gap:5px;width:74px" data-act="focusFriend" data-id="${id}"><span style="position:relative">${av(u)}${u.doing?'<span style="position:absolute;right:-1px;bottom:-1px;width:14px;height:14px;border-radius:50%;background:var(--good);border:2px solid var(--bg)"></span>':''}</span><b style="font-size:12px">${u.name}</b><span class="tiny" style="font-size:10.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:74px">${u.doing?A(u.doing).sport:u.share==='precise'?u.place:'Quartier '+AREA(u)}</span></button>`}).join('')}<button style="display:flex;flex-direction:column;align-items:center;gap:5px;width:74px" data-go="friends"><span class="avatar" style="background:var(--sky);color:var(--blue)">${I('plus')}</span><b style="font-size:12px">Ajouter</b><span class="tiny" style="font-size:10.5px">${S.reqIn.length} demande${S.reqIn.length>1?'s':''}</span></button></div></div>`;

SCREENS.friends=()=>{const fr=[...S.friends];const sugg=Object.keys(USERS).filter(id=>id!=='me'&&!S.friends.has(id)&&!S.reqIn.includes(id));
 const row=(id,right)=>{const u=U(id);return `<div class="item">${av(u)}<div class="col grow" data-go="user" data-id="${id}" style="cursor:pointer"><b style="font-size:14.5px">${u.name}, ${u.age} ${u.verified?`<span class="verified">${I('check')}</span>`:''}</b><span class="tiny" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${whereTxt(u)}</span></div>${right}</div>`};
 const active=fr.filter(id=>U(id).doing).length;
 return `<div class="sc">${head('Amis',`<button class="iconbtn" data-act="invite">${I('nav')}</button>`)}
 <div class="search">${I('search')}Rechercher un prénom, un pseudo…</div>
 <div class="card pad row" data-act="mapFriends" style="cursor:pointer;gap:12px;background:linear-gradient(135deg,var(--navy),var(--blue));color:#fff;border:0">${I('pin')}<div class="col grow"><b style="font-size:14px">Carte des amis</b><span class="tiny" style="color:rgba(255,255,255,.8)">${active} ami${active>1?'s':''} en activité · ${S.ghost?'toi : mode fantôme':'toi : '+S.shareMode.toLowerCase()}</span></div>${I('arrow')}</div>
 ${S.reqIn.length?`<div><div class="h3" style="margin-bottom:6px">Demandes reçues <span class="pill blue">${S.reqIn.length}</span></div><div class="list card" style="padding:0 14px">${S.reqIn.map(id=>row(id,`<div class="row" style="gap:6px"><button class="iconbtn" data-act="declineReq" data-id="${id}" aria-label="Refuser">${I('x')}</button><button class="iconbtn blue" data-act="acceptReq" data-id="${id}" aria-label="Accepter">${I('check')}</button></div>`)).join('')}</div></div>`:''}
 <div><div class="h3" style="margin-bottom:6px">Mes amis <span class="pill">${fr.length}</span></div><div class="list card" style="padding:0 14px">${fr.map(id=>row(id,`<div class="row" style="gap:6px"><button class="iconbtn" data-act="focusFriend" data-id="${id}" aria-label="Voir sur la carte">${I('pin')}</button><button class="iconbtn" data-go="chat" data-id="${C(id)?id:'yanis'}" aria-label="Message">${I('chat')}</button></div>`)).join('')||'<div class="item muted">Ajoute tes premiers amis ci-dessous.</div>'}</div></div>
 <div><div class="h3" style="margin-bottom:4px">Suggestions</div><p class="tiny" style="margin-bottom:8px">Personnes rencontrées en activité ou compatibles avec ton profil.</p><div class="list card" style="padding:0 14px">${sugg.map(id=>{const u=U(id);const why=u.score?`Match ${u.score} %`:'Activité en commun';return `<div class="item">${av(u)}<div class="col grow" data-go="user" data-id="${id}" style="cursor:pointer"><b style="font-size:14.5px">${u.name}, ${u.age}</b><span class="tiny">${why} · ${u.sports.map(s=>EMO[s[0]]).join(' ')}</span></div>${S.reqOut.has(id)?`<button class="pill" data-act="cancelReq" data-id="${id}">Envoyée</button>`:`<button class="pill blue" data-act="addFriend" data-id="${id}">${I('plus')} Ajouter</button>`}</div>`}).join('')||'<div class="item muted">Aucune suggestion pour le moment.</div>'}</div></div>
 <div class="card pad row" style="gap:10px;background:var(--sky);border-color:transparent">${I('lock')}<span class="tiny" style="color:var(--blue)">Seuls tes amis acceptés voient ta position, au quartier près par défaut. Mode fantôme disponible à tout moment.</span></div></div>`;};

const mapSeg=()=>`<div class="seg">${['Activités','Amis'].map(m=>`<button class="${S.mapMode===m?'on':''}" data-act="mapMode" data-v="${m}">${m==='Amis'?'👥':'📍'} ${m}</button>`).join('')}</div>`;
const _mapActivities=SCREENS.map;
SCREENS.map=()=>S.mapMode==='Amis'?mapFriendsScreen():_mapActivities().replace('<div class="mapwrap">',mapSeg()+'<div class="mapwrap">');
function mapSvg(inner,label){const land='M130 0H360V440H260c-20-12-45-22-70-14s-50-21-68-44c-14-20-12-52-6-82 6-28-20-48-30-74-10-24 6-44 26-56l58-4c5-1 6-16 0-17l-58-3c-8-16-8-34-4-46 4-20 10-60 22-100z';
 return `<svg viewBox="0 0 360 440" role="img" aria-label="${label}"><defs><pattern id="gridf" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#fff" stroke-width=".8" opacity=".45"/></pattern></defs><rect width="360" height="440" fill="#BFDDFF"/><path d="M0 120c30-10 50 10 80 0M0 260c30-12 60 12 90 0M0 400c30-10 50 10 80 0" stroke="#fff" stroke-width="2" fill="none" opacity=".7"/><path d="${land}" fill="#F4F8FE"/><path d="${land}" fill="url(#gridf)"/><ellipse cx="44" cy="150" rx="18" ry="8" fill="#F4F8FE"/><ellipse cx="52" cy="176" rx="22" ry="9" fill="#F4F8FE"/><circle cx="70" cy="158" r="5" fill="#F4F8FE"/><ellipse cx="150" cy="332" rx="30" ry="20" fill="#D7EFD9"/><ellipse cx="236" cy="112" rx="22" ry="14" fill="#D7EFD9"/><ellipse cx="300" cy="400" rx="30" ry="16" fill="#D7EFD9"/><path d="M182 160L206 214 190 286 152 332M206 214L300 398M182 160L236 112M112 184L98 216 126 300 128 380 196 416M206 214L216 176M130 60L182 160" stroke="#DCE6F5" stroke-width="5" fill="none" stroke-linecap="round"/><g font-family="Manrope,sans-serif" font-size="9" fill="#4A5B78" font-weight="700"><text x="196" y="140">Vieux-Port</text><text x="60" y="235">Corniche</text><text x="138" y="290">Prado</text><text x="140" y="398">Pointe Rouge</text><text x="210" y="434">Calanques</text><text x="28" y="140">Frioul</text><text x="226" y="100">Longchamp</text></g>${inner}</svg>`;}
function mapFriendsScreen(){const fr=[...S.friends].map(U);const sel=S.mapFriend?U(S.mapFriend):null;const active=fr.filter(u=>u.doing).length;
 const pins=fr.map(u=>`<g class="pin fpin ${S.mapFriend===u.id?'on':''}" data-act="focusFriend" data-id="${u.id}" transform="translate(${u.loc.x} ${u.loc.y})">${u.share==='area'?'<circle r="28" fill="#0F6BFF" opacity=".10"/>':''}<circle class="b" r="17"/><circle r="13" fill="${AVC[u.av]}"/><text text-anchor="middle" dy="4" font-size="10" font-weight="800" fill="#fff" font-family="Outfit,sans-serif">${u.ini}</text>${u.doing?'<circle cx="13" cy="-13" r="6" fill="#1BA672" stroke="#fff" stroke-width="2"/>':''}</g>`).join('');
 const me=S.ghost?'':`<g transform="translate(200 222)"><circle r="24" fill="#0F6BFF" opacity=".18"><animate attributeName="r" values="18;34;18" dur="2.4s" repeatCount="indefinite"/><animate attributeName="opacity" values=".25;0;.25" dur="2.4s" repeatCount="indefinite"/></circle><circle r="17" fill="#fff"/><circle r="13" fill="#0F6BFF"/><text text-anchor="middle" dy="4" font-size="10" font-weight="800" fill="#fff" font-family="Outfit,sans-serif">${USERS.me.ini}</text><text y="32" text-anchor="middle" font-size="9" font-weight="800" fill="#07234F" font-family="Manrope,sans-serif">Toi</text></g>`;
 return `<div class="sc">${head('Carte',`<button class="iconbtn ${S.ghost?'blue':''}" data-act="ghost" aria-label="Mode fantôme">${I('eye')}</button>`,false)}${mapSeg()}
 <div class="mapwrap"><div class="map-float">${S.ghost?'<span class="chip on" style="background:var(--navy)">👻 Mode fantôme · invisible pour tes amis</span>':`<span class="chip">👥 ${fr.length} amis</span><span class="chip">🟢 ${active} en activité</span><span class="chip">Toi · ${S.shareMode}</span>`}</div>${mapSvg(pins+me,'Carte des amis')}</div>
 ${sel?friendCard(sel):`<div class="hscroll">${fr.map(u=>`<button class="card pad" style="width:140px;display:flex;flex-direction:column;align-items:center;gap:6px;text-align:center;padding:12px" data-act="focusFriend" data-id="${u.id}">${av(u)}<b style="font-size:13px">${u.name}</b><span class="tiny" style="font-size:11px">${u.doing?'🟢 '+A(u.doing).sport:u.share==='precise'?u.place:'Quartier '+AREA(u)}</span></button>`).join('')}</div>`}
 <div class="card pad" style="display:flex;flex-direction:column;gap:12px"><div class="row" style="justify-content:space-between;gap:10px"><div class="col"><b style="font-size:14px">Ma position</b><span class="tiny">Visible par mes amis uniquement</span></div><div class="seg" style="width:auto">${['Quartier','Précis'].map(m=>`<button class="${S.shareMode===m?'on':''}" data-act="shareMode" data-v="${m}">${m}</button>`).join('')}</div></div><div class="row" style="justify-content:space-between"><div class="col"><b style="font-size:14px">Mode fantôme</b><span class="tiny">Tu vois tes amis, ils ne te voient pas</span></div><span class="toggle ${S.ghost?'on':''}" data-act="ghost"></span></div></div>
 <p class="tiny" style="text-align:center">Position jamais visible par les autres membres ni affichée à l'adresse exacte. Désactivable dans Confidentialité.</p></div>`;}
function friendCard(u){const a=u.doing&&A(u.doing);return `<div class="card pad fade" style="display:flex;flex-direction:column;gap:10px"><div class="row">${av(u)}<div class="col grow" data-go="user" data-id="${u.id}" style="cursor:pointer"><b style="font-size:15px">${u.name}, ${u.age} ${u.verified?`<span class="verified">${I('check')}</span>`:''}</b><span class="tiny">${u.doing?`📍 ${u.place} · ${u.seen}`:whereTxt(u)}</span></div><button class="iconbtn" data-act="focusFriend" data-id="" aria-label="Fermer">${I('x')}</button></div>${a?`<div class="row" style="background:var(--sky);border-radius:12px;padding:10px;cursor:pointer" data-go="activity" data-id="${a.id}"><span style="font-size:20px">${EMO[a.sport]}</span><div class="col grow"><b style="font-size:13px">En activité · ${a.title}</b><span class="tiny">${a.place} · ${a.n}/${a.max} participants · ${a.level}</span></div>${I('arrow')}</div>`:''}<div class="grid2"><button class="btn btn-ghost btn-sm" data-go="chat" data-id="${C(u.id)?u.id:'yanis'}">${I('chat')} Message</button>${a&&!S.joined.has(a.id)?`<button class="btn btn-primary btn-sm" data-act="join" data-id="${a.id}">Rejoindre ${u.name}</button>`:`<button class="btn btn-primary btn-sm" data-act="inviteUser" data-id="${u.id}">Proposer une activité</button>`}</div></div>`;}

Object.assign(ACTIONS,{
 mapMode(_,v){S.mapMode=v;S.mapFriend=null;S.mapPlace=null;render();},
 mapFriends(){S.mapMode='Amis';S.mapFriend=null;go('map');},
 openFriends(){go('friends');},
 focusFriend(id){S.mapMode='Amis';S.mapFriend=id||null;if(S.screen!=='map')go('map');else render();},
 ghost(){S.ghost=!S.ghost;render();toast(S.ghost?'Mode fantôme activé : tes amis ne te voient plus':'Tu es de nouveau visible par tes amis','eye');},
 shareMode(_,v){S.shareMode=v;render();toast('Position partagée : '+v.toLowerCase(),'pin');},
 addFriend(id){S.reqOut.add(id);render();toast(`Demande envoyée à ${U(id).name}`,'send');if(['mehdi','hugo','nour'].includes(id))setTimeout(()=>{if(!S.reqOut.has(id))return;S.reqOut.delete(id);S.friends.add(id);render();toast(`${U(id).name} a accepté ta demande 🎉`,'users');},1800);},
 cancelReq(id){S.reqOut.delete(id);render();toast('Demande annulée','x');},
 acceptReq(id){S.reqIn=S.reqIn.filter(x=>x!==id);S.friends.add(id);closeSheet();render();toast(`Toi et ${U(id).name} êtes maintenant amis`,'users');},
 declineReq(id){S.reqIn=S.reqIn.filter(x=>x!==id);render();toast('Demande refusée','x');},
 friendMenu(id){sheet(`<div class="h3">${U(id).name} · ami</div><div class="list"><div class="item" data-act="focusFriend" data-id="${id}" style="cursor:pointer">${I('pin')}<b style="font-size:14px">Voir sur la carte</b></div><div class="item" data-go="chat" data-id="${C(id)?id:'yanis'}" style="cursor:pointer">${I('chat')}<b style="font-size:14px">Envoyer un message</b></div><div class="item" data-act="inviteUser" data-id="${id}" style="cursor:pointer">${I('activity')}<b style="font-size:14px">Proposer une activité</b></div><div class="item" data-act="removeFriend" data-id="${id}" style="cursor:pointer;color:var(--bad)">${I('x')}<b style="font-size:14px">Retirer de mes amis</b></div></div>`);},
 removeFriend(id){S.friends.delete(id);closeSheet();render();toast(`${U(id).name} ne fait plus partie de tes amis`,'x');},
 invite(){toast('Lien d\'invitation copié · marsup.app/i/lola','nav');},
});
</script>
