<script>
/* ---------- Site : activités populaires, sélecteur d'écrans, ouverture de la démo ---------- */
const SCREEN_LIST=[['welcome','Landing app'],['signup','Inscription'],['verify','Vérification d\'identité'],['home','Accueil / fil'],['discover','Matching'],['activities','Activités'],['activity','Détail activité'],['messages','Messages'],['chat','Chat'],['map','Carte'],['friendsmap','Carte des amis'],['friends','Amis'],['rank','Classement'],['shop','Boutique'],['events','Événements'],['notifications','Notifications'],['ai','IA mars’up'],['profile','Profil'],['settings','Confidentialité'],['admin','Dashboard admin']];
$('#pop-grid').innerHTML=ACTS.filter(a=>a.pop).map(a=>`<article class="pop-card" data-open="activity" data-id="${a.id}"><div class="scene">${scene(a.kind)}<span class="tag">${EMO[a.sport]} ${a.sport}</span></div><div class="body"><h3>${a.title}</h3><div class="meta"><span>📍 ${a.place}</span><span>🗓 ${a.day} ${a.time}</span></div><div class="meta"><span>👥 ${a.n} participants</span><span>${EMO[a.sport]} ${a.level}</span></div></div></article>`).join('');
const chipsHtml=SCREEN_LIST.map(([id,l])=>`<button class="chip" data-open="${id}">${l}</button>`).join('');
$('#screen-chips').innerHTML=chipsHtml;$('#phone-controls').innerHTML=chipsHtml;

function openDemo(screen,id){
  if(screen==='admin'){document.body.classList.remove('demo-open');$('#admin').scrollIntoView({behavior:'smooth'});return;}
  if(screen==='friendsmap'){S.mapMode='Amis';S.mapFriend=null;screen='map';}else if(screen==='map'){S.mapMode='Activités';}
  if(screen==='signup'){S.signup.step=1;}if(screen==='verify'){S.verify.step=0;}
  const p=id?{id}:screen==='activity'?{id:'sunset'}:screen==='chat'?{id:'running'}:{};
  go(screen,p);
  if(window.matchMedia('(max-width:900px)').matches){if(!document.body.classList.contains('demo-open')){document.body.classList.add('demo-open');try{history.pushState({demo:1},'')}catch(_){}}}
  else{const r=$('#phone-col').getBoundingClientRect();if(r.top<0||r.bottom>window.innerHeight)window.scrollTo({top:Math.max(0,window.scrollY+r.top-90),behavior:'smooth'});}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(!b)return;openDemo(b.dataset.open,b.dataset.id);});
const closeDemo=()=>document.body.classList.remove('demo-open');
$('#phone-close').addEventListener('click',()=>{if(history.state&&history.state.demo)history.back();else closeDemo();});
window.addEventListener('popstate',()=>{if(document.body.classList.contains('demo-open'))closeDemo();});

/* ---------- Admin ---------- */
const ADM={tab:'overview',pending:[['Tom D.','25 ans · 2e','Passeport','il y a 12 min','tom'],['Amine K.','22 ans · 3e','CNI','il y a 40 min','mehdi'],['Julie P.','20 ans · 8e','CNI','il y a 2 h','camille']],reports:[['#R-2041','Faux profil / usurpation','Signalé par Léa','Profil : « Max_13 »','Ouvert','bad'],['#R-2039','Contenu hors sujet','Signalé par Inès','Message dans « Nouveaux à Marseille »','En cours','warn'],['#R-2035','Comportement inapproprié','Signalé par Camille','Chat privé','Résolu · compte suspendu','good'],['#R-2031','Spam / publicité','Signalé par Hugo','Publication','Résolu · contenu retiré','good']],blocked:[['Max_13','Usurpation confirmée','Suspendu 30 j'],['Kev.Pro','Démarchage commercial','Banni']],sent:[]};
const SIGN=[42,55,48,61,70,66,80,74,88,95,90,104,112,121];
const DAYS=['19','20','21','22','23','24','25','26','27','28','29','30','1','2'];
const kpi=(l,v,d,up=true)=>`<div class="kpi"><span>${l}</span><b>${v}</b><span class="d ${up?'up':'dn'}">${I('trend')}${d}</span></div>`;
const st=(t,c)=>`<span class="pill ${c}">${t}</span>`;
const ADMIN_VIEWS={
 overview:()=>`<div class="row" style="justify-content:space-between;flex-wrap:wrap;gap:10px"><h3>Vue d'ensemble</h3><div class="seg" style="width:auto"><button>7 j</button><button class="on">14 j</button><button>30 j</button></div></div>
  <div class="kpis">${kpi('Utilisateurs inscrits','4 218','+6,1 % vs 14 j')}${kpi('Nouveaux inscrits (14 j)','1 106','+18 %')}${kpi('Utilisateurs actifs (7 j)','2 734','+4,2 %')}${kpi('Activités créées (14 j)','612','+9 %')}${kpi('Activités complètes','231','38 % du total')}${kpi('Messages (14 j)','48 920','+22 %')}${kpi('Événements à venir','5','2 partenaires')}${kpi('Taux de participation','87 %','−1,2 pt',false)}</div>
  <div class="charts"><div class="chart"><h4>Nouveaux inscrits par jour <small>14 derniers jours · total 1 106</small></h4><div class="bars">${SIGN.map((v,i)=>`<div class="bar ${i===SIGN.length-1?'hi':''}" style="--v:${v/121*100}"><span class="tip">${DAYS[i]} ${i<12?'sept.':'oct.'} · ${v} inscrits</span></div>`).join('')}</div><div class="bar-x">${DAYS.map((d,i)=>`<span>${i%2?'':d}</span>`).join('')}</div></div>
  <div class="chart"><h4>Participation par activité <small>inscrits présents</small></h4><div class="hbars">${[['Running',94],['Beach-volley',91],['Yoga',89],['Randonnée',88],['Basket',84],['Football',79],['Nautique',76]].map(([n,v])=>`<div class="hbar"><span>${EMO[n]} ${n}</span><div class="trk"><i style="--v:${v}"></i></div><b>${v} %</b></div>`).join('')}</div></div></div>
  <div class="admin-two"><div class="panel"><h4>À traiter</h4><div class="list"><div class="item" data-adm="users" style="cursor:pointer">${I('shield')}<div class="col grow"><b style="font-size:14px">${ADM.pending.length} vérifications en attente</b><span class="tiny">Statut « à revoir » renvoyé par le prestataire</span></div>${I('arrow')}</div><div class="item" data-adm="reports" style="cursor:pointer">${I('flag')}<div class="col grow"><b style="font-size:14px">${ADM.reports.filter(r=>r[4]!=='Résolu').length} signalements ouverts</b><span class="tiny">Délai moyen de traitement : 6 h</span></div>${I('arrow')}</div><div class="item" data-adm="events" style="cursor:pointer">${I('calendar')}<div class="col grow"><b style="font-size:14px">Beach Day · 6 places restantes</b><span class="tiny">Dimanche 15h · envoyer un rappel ?</span></div>${I('arrow')}</div></div></div>
  <div class="panel"><h4>Activité en direct</h4><div class="list">${[['Lola M. a rejoint « Sunset Run »','il y a 1 min'],['Nouveau groupe créé par l\'IA : Hand & running débutant 5e','il y a 4 min'],['Léa R. a publié une photo · Catalans','il y a 9 min'],['Inscription validée : Nour B. (vérifiée)','il y a 15 min'],['Événement partenaire soumis : Tournoi 3x3 du Prado','il y a 32 min']].map(([t,d])=>`<div class="item"><span class="avatar sm" style="background:var(--sky);color:var(--blue)">${I('activity')}</span><div class="col grow"><span style="font-size:13.5px">${t}</span><span class="tiny">${d}</span></div></div>`).join('')}</div></div></div>`,
 users:()=>`<div class="row" style="justify-content:space-between;flex-wrap:wrap;gap:10px"><h3>Utilisateurs</h3><div class="search" style="width:260px">${I('search')}Nom, e-mail, secteur…</div></div>
  <div class="kpis">${kpi('Total','4 218','+6,1 %')}${kpi('Vérifiés','3 902','92,5 %')}${kpi('En attente','3','à traiter')}${kpi('Bloqués / suspendus','14','0,3 %')}</div>
  <div class="panel"><h4>Vérifications à revoir</h4><div class="tbl-wrap"><table><thead><tr><th>Utilisateur</th><th>Document</th><th>Prestataire</th><th>Reçu</th><th>Action</th></tr></thead><tbody>${ADM.pending.length?ADM.pending.map((p,i)=>`<tr><td><div class="row">${av(p[4],'sm')}<div class="col"><b>${p[0]}</b><span class="tiny">${p[1]}</span></div></div></td><td>${p[2]}</td><td>${st('À revoir · visage 71 %','warn')}</td><td class="tiny">${p[3]}</td><td><div class="tbl-actions"><button class="btn-xs ok" data-adm-act="approve" data-i="${i}">Valider</button><button class="btn-xs ko" data-adm-act="reject" data-i="${i}">Refuser</button><button class="btn-xs nt">Redemander</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="muted" style="text-align:center">Aucune vérification en attente 🎉</td></tr>'}</tbody></table></div><p class="tiny">Les documents ne sont jamais affichés ici : seul le score de correspondance et le statut renvoyés par le prestataire sont consultés. Conformité RGPD · minimisation.</p></div>
  <div class="panel"><h4>Derniers inscrits</h4><div class="tbl-wrap"><table><thead><tr><th>Membre</th><th>Secteur</th><th>Sports</th><th>Statut</th><th>Activités</th><th></th></tr></thead><tbody>${['nour','hugo','ines','camille','mehdi','lea','yanis'].map(id=>{const u=U(id);return `<tr><td><div class="row">${av(u,'sm')}<div class="col"><b>${u.name} ${u.ini[1].toLowerCase()}.</b><span class="tiny">${u.age} ans</span></div></div></td><td>${u.sector}</td><td>${u.sports.map(s=>EMO[s[0]]).join(' ')}</td><td>${u.verified?st('Vérifié','good'):st('Non vérifié','warn')}</td><td>${3+u.age%7}</td><td><div class="tbl-actions"><button class="btn-xs nt">Voir</button><button class="btn-xs ko">Bloquer</button></div></td></tr>`}).join('')}</tbody></table></div></div>`,
 reports:()=>`<div class="row" style="justify-content:space-between;flex-wrap:wrap;gap:10px"><h3>Signalements & modération</h3><div class="seg" style="width:auto"><button class="on">Tous</button><button>Ouverts</button><button>Résolus</button></div></div>
  <div class="kpis">${kpi('Ouverts','2','à traiter')}${kpi('Délai moyen','6 h','−2 h',true)}${kpi('Résolus (30 j)','47','98 % sous 24 h')}${kpi('Publications masquées','9','ce mois')}</div>
  <div class="panel"><h4>Signalements</h4><div class="tbl-wrap"><table><thead><tr><th>Réf.</th><th>Motif</th><th>Source</th><th>Cible</th><th>Statut</th><th>Action</th></tr></thead><tbody>${ADM.reports.map((r,i)=>`<tr><td class="tiny">${r[0]}</td><td><b>${r[1]}</b></td><td>${r[2]}</td><td>${r[3]}</td><td>${st(r[4],r[5])}</td><td><div class="tbl-actions">${r[4].startsWith('Résolu')?'<button class="btn-xs nt">Détails</button>':`<button class="btn-xs nt" data-adm-act="resolve" data-i="${i}" data-v="avertissement">Avertir</button><button class="btn-xs ko" data-adm-act="resolve" data-i="${i}" data-v="suspension">Suspendre</button><button class="btn-xs ok" data-adm-act="resolve" data-i="${i}" data-v="classement">Classer</button>`}</div></td></tr>`).join('')}</tbody></table></div></div>
  <div class="admin-two"><div class="panel"><h4>Publications à modérer</h4><div class="list">${[['Hugo · Calanque de Sormiou','Détecté : aucun problème · publié'],['Compte « Kev.Pro » · Cours Julien','Détecté : lien commercial · masqué en attente']].map(([t,s],i)=>`<div class="item"><span class="avatar sm" style="background:var(--sky);color:var(--blue)">${I('image')}</span><div class="col grow"><b style="font-size:14px">${t}</b><span class="tiny">${s}</span></div><div class="tbl-actions"><button class="btn-xs ok">Garder</button><button class="btn-xs ko">Retirer</button></div></div>`).join('')}</div></div>
  <div class="panel"><h4>Comptes bloqués / suspendus</h4><div class="list">${ADM.blocked.map(b=>`<div class="item">${I('ban')}<div class="col grow"><b style="font-size:14px">${b[0]}</b><span class="tiny">${b[1]}</span></div>${st(b[2],'bad')}<button class="btn-xs nt">Réviser</button></div>`).join('')}</div></div></div>`,
 events:()=>`<div class="row" style="justify-content:space-between;flex-wrap:wrap;gap:10px"><h3>Activités & événements</h3><button class="btn btn-primary btn-sm" data-adm-act="newEvent">${I('plus')} Créer un événement</button></div>
  <div class="kpis">${kpi('Activités cette semaine','312','+9 %')}${kpi('Complètes','118','38 %')}${kpi('Événements à venir','5','2 partenaires')}${kpi('Groupes actifs','164','+12')}</div>
  <div class="panel"><h4>Événements</h4><div class="tbl-wrap"><table><thead><tr><th>Événement</th><th>Organisateur</th><th>Date</th><th>Inscrits</th><th>Statut</th><th>Actions</th></tr></thead><tbody>${EVENTS.map(e=>`<tr><td><b>${e.title}</b><div class="tiny">${e.place}</div></td><td>${e.by}</td><td>${e.day} · ${e.time}</td><td><div class="row" style="gap:8px"><div class="progress" style="width:70px"><i style="width:${e.n/e.max*100}%"></i></div><span class="tiny">${e.n}/${e.max}</span></div></td><td>${e.id==='3x3'?st('À valider','warn'):st('Publié','good')}</td><td><div class="tbl-actions"><button class="btn-xs nt" data-adm-act="toastA" data-v="Modification de « ${e.title} »">${I('edit')}</button><button class="btn-xs nt" data-adm-act="toastA" data-v="Rappel envoyé aux ${e.n} inscrits">${I('bell')}</button><button class="btn-xs ko" data-adm-act="delEvent" data-i="${e.id}">${I('trash')}</button></div></td></tr>`).join('')}</tbody></table></div></div>
  <div class="admin-two"><div class="panel"><h4>Activités les plus rejointes (7 j)</h4><div class="hbars">${ACTS.filter(a=>a.pop).map(a=>`<div class="hbar"><span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${a.title}</span><div class="trk"><i style="--v:${a.n/a.max*100}"></i></div><b>${a.n}/${a.max}</b></div>`).join('')}</div></div>
  <div class="panel"><h4>Groupes</h4><div class="list">${[['Running Marseille 🏃','12 membres · très actif'],['Beach-volley Catalans 🏐','18 membres · actif'],['Nouveaux à Marseille 👋','340 membres · communautaire'],['Hand & running débutant 5e 🏃','9 membres · créé par l\'IA']].map(g=>`<div class="item"><div class="col grow"><b style="font-size:14px">${g[0]}</b><span class="tiny">${g[1]}</span></div><div class="tbl-actions"><button class="btn-xs nt">Gérer</button><button class="btn-xs ko">Archiver</button></div></div>`).join('')}</div></div></div>`,
 notifs:()=>`<h3>Notifications</h3><div class="admin-two"><div class="panel"><h4>Envoyer une notification</h4>
  <div class="field"><label for="n-aud">Audience</label><select id="n-aud" class="input"><option>Inscrits au Beach Day (24)</option><option>Membres du 6e, 7e, 8e (1 240)</option><option>Runners niveau débutant (612)</option><option>Tous les membres vérifiés (3 902)</option></select></div>
  <div class="field"><label for="n-title">Titre</label><input id="n-title" class="input" value="Beach Day dimanche 15h 🌊"></div>
  <div class="field"><label for="n-body">Message</label><textarea id="n-body" class="input" rows="3">Plus que 6 places ! Pense à prendre de l'eau et ta crème solaire. Rendez-vous à la plage des Catalans.</textarea></div>
  <div class="field"><label>Type</label><div class="chips">${['Rappel d\'événement','Nouvel événement','Activité proche','Recommandation IA','Information'].map((t,i)=>`<span class="chip ${i===0?'on':''}">${t}</span>`).join('')}</div></div>
  <div class="row" style="justify-content:space-between"><label class="row" style="gap:8px;font-size:13px"><span class="toggle" data-adm-act="tgl"></span>Programmer l'envoi</label><button class="btn btn-primary btn-sm" data-adm-act="sendNotif">${I('send')} Envoyer</button></div></div>
  <div class="panel"><h4>Aperçu & historique</h4><div class="card pad" style="background:var(--surface)"><div class="row"><svg class="mark" style="height:28px"><use href="#mu-mark"/></svg><div class="col grow"><b style="font-size:14px" id="n-prev-t">Beach Day dimanche 15h 🌊</b><span class="muted" id="n-prev-b">Plus que 6 places ! Pense à prendre de l'eau…</span></div><span class="tiny">maintenant</span></div></div>
  <div class="list" id="n-hist">${ADM.sent.map(s=>`<div class="item">${I('check')}<div class="col grow"><b style="font-size:14px">${s[0]}</b><span class="tiny">${s[1]}</span></div>${st('Envoyée','good')}</div>`).join('')}<div class="item">${I('bell')}<div class="col grow"><b style="font-size:14px">3 activités ce soir près de toi</b><span class="tiny">Auto · 1 240 destinataires · ouverture 41 %</span></div>${st('Envoyée','good')}</div><div class="item">${I('sparkles')}<div class="col grow"><b style="font-size:14px">Recommandation IA : groupes personnalisés</b><span class="tiny">Auto · 612 destinataires · ouverture 53 %</span></div>${st('Envoyée','good')}</div><div class="item">${I('calendar')}<div class="col grow"><b style="font-size:14px">Run Club mercredi 19h</b><span class="tiny">Programmée · mar. 19h00 · 38 destinataires</span></div>${st('Programmée','blue')}</div></div></div></div>`,
};
const ADMIN_TABS=[['overview','Vue d\'ensemble','chart'],['users','Utilisateurs','users'],['reports','Signalements','flag'],['events','Activités & événements','calendar'],['notifs','Notifications','bell']];
function renderAdmin(){$('#admin-nav').innerHTML=ADMIN_TABS.map(([id,l,ic])=>`<button class="${ADM.tab===id?'on':''}" data-adm="${id}">${I(ic)}${l}${id==='users'&&ADM.pending.length?`<span class="cnt">${ADM.pending.length}</span>`:id==='reports'?`<span class="cnt">${ADM.reports.filter(r=>!r[4].startsWith('Résolu')).length}</span>`:''}</button>`).join('');$('#admin-main').innerHTML=`<div class="fade">${ADMIN_VIEWS[ADM.tab]()}</div>`;}
function admToast(m){const t=document.createElement('div');t.className='toast';t.style.cssText='position:fixed;left:50%;transform:translateX(-50%);bottom:24px;width:min(420px,calc(100% - 32px));z-index:200';t.innerHTML=I('check')+'<span>'+m+'</span>';document.body.appendChild(t);setTimeout(()=>t.remove(),2600);}
$('#admin').addEventListener('click',e=>{const t=e.target.closest('[data-adm],[data-adm-act]');if(!t)return;
 if(t.dataset.adm){ADM.tab=t.dataset.adm;renderAdmin();return;}
 const a=t.dataset.admAct,i=t.dataset.i,v=t.dataset.v;
 if(a==='approve'){const p=ADM.pending.splice(i,1)[0];renderAdmin();admToast(`${p[0]} : compte vérifié, badge attribué.`);}
 if(a==='reject'){const p=ADM.pending.splice(i,1)[0];renderAdmin();admToast(`${p[0]} : vérification refusée, utilisateur notifié.`);}
 if(a==='resolve'){const r=ADM.reports[i];r[4]=v==='suspension'?'Résolu · compte suspendu':v==='avertissement'?'Résolu · avertissement':'Résolu · classé';r[5]='good';renderAdmin();admToast(`${r[0]} traité (${v}). Signalant informé.`);}
 if(a==='delEvent'){const k=EVENTS.findIndex(x=>x.id===i);if(k>-1){const e=EVENTS.splice(k,1)[0];renderAdmin();admToast(`« ${e.title} » supprimé, ${e.n} inscrits prévenus.`);}}
 if(a==='newEvent'){EVENTS.push({id:'new'+Date.now(),title:'MARS’UP YOGA SUNRISE 🧘',sub:'Yoga collectif',kind:'yoga',place:'Vallon des Auffes',day:'Samedi 25 oct.',time:'7h30',n:0,max:40,by:'mars’up',desc:'Séance collective au lever du soleil.',who:[]});renderAdmin();admToast('Événement créé en brouillon : « MARS’UP YOGA SUNRISE »');}
 if(a==='toastA')admToast(v);
 if(a==='tgl')t.classList.toggle('on');
 if(a==='sendNotif'){const ti=$('#n-title').value,au=$('#n-aud').value;ADM.sent.unshift([ti,'Manuel · '+au+' · à l\'instant']);renderAdmin();admToast('Notification envoyée à « '+au+' »');}
});
$('#admin').addEventListener('input',e=>{if(e.target.id==='n-title')$('#n-prev-t').textContent=e.target.value;if(e.target.id==='n-body')$('#n-prev-b').textContent=e.target.value.slice(0,48)+'…';});

/* ---------- Démarrage ---------- */
renderAdmin();
render();
</script>
